### ISSUE TITLE
Run Profiles for RegPack

### ISSUE THREAD

**Issue by mahudu97** [mahudu97/fyp-scratch#2]
List within `logs`

AWS c5.9xlarge setup

**Comment by aswaathb** [comment]
I'd recommend a c5<sup>[1](https://aws.amazon.com/ec2/instance-types/c5/)</sup> or a m5<sup>[2](https://aws.amazon.com/ec2/instance-types/m5/)</sup> AWS EC2 instance for this project, if you aren't already using it.

I've heard great things about the compute optimised instances.

<sup>[1,2]</sup> Not sure which particular model is best suited for this project, but from a quick glance, I'd say the c5.9xlarge instance is a great starting point  :sweat_smile:

**Comment by mahudu97** [comment]
Need to further breakdown / better target specific matrices for PyFR suite

**Comment by mahudu97** [comment]
Collected for `synth` at sampling freq. `0.1ms`
