### ISSUE TITLE
Sparse Dense Matrix Multiplication algorithm 

### ISSUE THREAD

**Issue by CosimoRulli** [mahudu97/fyp-scratch#4]
Hi, 
I saw you are working on a thesis on sparse dense multiplication algorithm with the csr format from [this](https://github.com/hfp/libxsmm/issues/378) issue in the libxsmm github page. I am working on a related topic and I would like to discuss it with you privately. If you are interested too,  please contact me at cosimo.rulli@phd.unipi.it for additional detail.

**Comment by mahudu97** [comment]
emailed!
